web: python manage.py runserver 0.0.0.0:8001
worker: python manage.py celery worker -E --loglevel=INFO
scheduler: python manage.py celery beat
monitor: python manage.py celery flower --broker=amqp://guest:guest@localhost:5672// --address=0.0.0.0 --port=5555